nome = input('Qual seu nome? ')
idade = input('Qual sua idade? ')
peso = input('Qual seu peso? ')
dia = input()
mes = input()
ano = input()
print(nome, idade, peso)
print('Ola', nome)
print('Voce nasceu no dia', dia, 'de', mes, 'de', ano)
