var = input('Digite algo: ')
print('Tipo primitivo: {}'.format(type(var)))
print('É apenas espaço(s)? {}'.format(var.isspace()))
print('É alfabético? {}'.format(var.isalpha()))
print('É alfanumérico? {}'.format(var.isalnum()))
print('É apenas número(s)? {}'.format(var.isnumeric()))
print('Está apenas em maiúsculo? {}'.format(var.isupper()))
print('Está apenas em minúsculo? {}'.format(var.islower()))
print('Está capitalizada? {}'.format(var.istitle()))
